// Code generated by protoc-gen-go. DO NOT EDIT.
// source: adventar/v1/resources.proto

package adventar_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Date struct {
	Year                 int32    `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month                int32    `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	Day                  int32    `protobuf:"varint,3,opt,name=day,proto3" json:"day,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Date) Reset()         { *m = Date{} }
func (m *Date) String() string { return proto.CompactTextString(m) }
func (*Date) ProtoMessage()    {}
func (*Date) Descriptor() ([]byte, []int) {
	return fileDescriptor_76df1f65f3b52923, []int{0}
}

func (m *Date) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Date.Unmarshal(m, b)
}
func (m *Date) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Date.Marshal(b, m, deterministic)
}
func (m *Date) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Date.Merge(m, src)
}
func (m *Date) XXX_Size() int {
	return xxx_messageInfo_Date.Size(m)
}
func (m *Date) XXX_DiscardUnknown() {
	xxx_messageInfo_Date.DiscardUnknown(m)
}

var xxx_messageInfo_Date proto.InternalMessageInfo

func (m *Date) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *Date) GetMonth() int32 {
	if m != nil {
		return m.Month
	}
	return 0
}

func (m *Date) GetDay() int32 {
	if m != nil {
		return m.Day
	}
	return 0
}

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IconUrl              string   `protobuf:"bytes,3,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_76df1f65f3b52923, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetIconUrl() string {
	if m != nil {
		return m.IconUrl
	}
	return ""
}

type Calendar struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Owner                *User    `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Year                 int32    `protobuf:"varint,5,opt,name=year,proto3" json:"year,omitempty"`
	EntryCount           int32    `protobuf:"varint,6,opt,name=entry_count,json=entryCount,proto3" json:"entry_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Calendar) Reset()         { *m = Calendar{} }
func (m *Calendar) String() string { return proto.CompactTextString(m) }
func (*Calendar) ProtoMessage()    {}
func (*Calendar) Descriptor() ([]byte, []int) {
	return fileDescriptor_76df1f65f3b52923, []int{2}
}

func (m *Calendar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Calendar.Unmarshal(m, b)
}
func (m *Calendar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Calendar.Marshal(b, m, deterministic)
}
func (m *Calendar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Calendar.Merge(m, src)
}
func (m *Calendar) XXX_Size() int {
	return xxx_messageInfo_Calendar.Size(m)
}
func (m *Calendar) XXX_DiscardUnknown() {
	xxx_messageInfo_Calendar.DiscardUnknown(m)
}

var xxx_messageInfo_Calendar proto.InternalMessageInfo

func (m *Calendar) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Calendar) GetOwner() *User {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *Calendar) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Calendar) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Calendar) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *Calendar) GetEntryCount() int32 {
	if m != nil {
		return m.EntryCount
	}
	return 0
}

type Entry struct {
	Id                   int64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Owner                *User     `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Calendar             *Calendar `protobuf:"bytes,3,opt,name=calendar,proto3" json:"calendar,omitempty"`
	Date                 *Date     `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	Comment              string    `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	Url                  string    `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	Title                string    `protobuf:"bytes,7,opt,name=title,proto3" json:"title,omitempty"`
	ImageUrl             string    `protobuf:"bytes,8,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_76df1f65f3b52923, []int{3}
}

func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (m *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(m, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Entry) GetOwner() *User {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *Entry) GetCalendar() *Calendar {
	if m != nil {
		return m.Calendar
	}
	return nil
}

func (m *Entry) GetDate() *Date {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *Entry) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *Entry) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Entry) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Entry) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*Date)(nil), "adventar.v1.Date")
	proto.RegisterType((*User)(nil), "adventar.v1.User")
	proto.RegisterType((*Calendar)(nil), "adventar.v1.Calendar")
	proto.RegisterType((*Entry)(nil), "adventar.v1.Entry")
}

func init() { proto.RegisterFile("adventar/v1/resources.proto", fileDescriptor_76df1f65f3b52923) }

var fileDescriptor_76df1f65f3b52923 = []byte{
	// 338 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xc1, 0x4e, 0xeb, 0x30,
	0x10, 0x54, 0xda, 0xa4, 0x4d, 0x36, 0xd2, 0xd3, 0xc3, 0x02, 0x29, 0xa8, 0x07, 0xaa, 0x48, 0x08,
	0x4e, 0xa9, 0x5a, 0xfe, 0x80, 0xd2, 0x1f, 0xb0, 0xd4, 0x73, 0x65, 0xec, 0x15, 0x58, 0x4a, 0xec,
	0xca, 0x71, 0x8b, 0xfa, 0x57, 0xfc, 0x1e, 0x37, 0xe4, 0x6d, 0x53, 0x02, 0xdc, 0xb8, 0xed, 0xcc,
	0x6c, 0x26, 0xbb, 0xb3, 0x86, 0x89, 0x50, 0x7b, 0x34, 0x5e, 0xb8, 0xd9, 0x7e, 0x3e, 0x73, 0xd8,
	0xda, 0x9d, 0x93, 0xd8, 0x56, 0x5b, 0x67, 0xbd, 0x65, 0x79, 0x27, 0x56, 0xfb, 0x79, 0xf9, 0x08,
	0xf1, 0x93, 0xf0, 0xc8, 0x18, 0xc4, 0x07, 0x14, 0xae, 0x88, 0xa6, 0xd1, 0x7d, 0xc2, 0xa9, 0x66,
	0x97, 0x90, 0x34, 0xd6, 0xf8, 0xd7, 0x62, 0x40, 0xe4, 0x11, 0xb0, 0xff, 0x30, 0x54, 0xe2, 0x50,
	0x0c, 0x89, 0x0b, 0x65, 0xb9, 0x82, 0x78, 0xdd, 0xa2, 0x63, 0xff, 0x60, 0xa0, 0x15, 0x39, 0x0c,
	0xf9, 0x40, 0xab, 0xe0, 0x69, 0x44, 0x83, 0xf4, 0x79, 0xc6, 0xa9, 0x66, 0xd7, 0x90, 0x6a, 0x69,
	0xcd, 0x66, 0xe7, 0x6a, 0xb2, 0xc8, 0xf8, 0x38, 0xe0, 0xb5, 0xab, 0xcb, 0xf7, 0x08, 0xd2, 0xa5,
	0xa8, 0xd1, 0x28, 0xf1, 0xdb, 0xeb, 0x0e, 0x12, 0xfb, 0x66, 0xd0, 0x91, 0x59, 0xbe, 0xb8, 0xa8,
	0x7a, 0x4b, 0x54, 0xe1, 0xef, 0xfc, 0xa8, 0x87, 0xa1, 0xbd, 0xf6, 0x35, 0x9e, 0xdc, 0x8f, 0x80,
	0x4d, 0x21, 0x57, 0xd8, 0x4a, 0xa7, 0xb7, 0x5e, 0x5b, 0x53, 0xc4, 0xa4, 0xf5, 0xa9, 0x73, 0x00,
	0x49, 0x2f, 0x80, 0x1b, 0xc8, 0xd1, 0x78, 0x77, 0xd8, 0x48, 0xbb, 0x33, 0xbe, 0x18, 0x91, 0x04,
	0x44, 0x2d, 0x03, 0x53, 0x7e, 0x44, 0x90, 0xac, 0x02, 0xfc, 0xfb, 0xbc, 0x73, 0x48, 0xe5, 0x69,
	0x69, 0x1a, 0x39, 0x5f, 0x5c, 0x7d, 0xeb, 0xed, 0x12, 0xe1, 0xe7, 0x36, 0x76, 0x0b, 0xb1, 0x12,
	0x1e, 0x69, 0x8b, 0x9f, 0xd6, 0xe1, 0x98, 0x9c, 0x64, 0x56, 0xc0, 0x58, 0xda, 0xa6, 0x41, 0xe3,
	0x69, 0xa9, 0x8c, 0x77, 0x30, 0x9c, 0x30, 0xe4, 0x3f, 0x22, 0x36, 0x94, 0x5f, 0xa9, 0x8d, 0xfb,
	0xa9, 0x4d, 0x20, 0xd3, 0x8d, 0x78, 0x41, 0xba, 0x56, 0x4a, 0x4a, 0x4a, 0xc4, 0xda, 0xd5, 0xcf,
	0x23, 0x7a, 0x4d, 0x0f, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0b, 0xf5, 0x90, 0x7e, 0x6c, 0x02,
	0x00, 0x00,
}
