// Code generated by protoc-gen-go. DO NOT EDIT.
// source: adventar/v1/rpc_messages.proto

package adventar_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListCalendarsRequest struct {
	Year                 int64    `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCalendarsRequest) Reset()         { *m = ListCalendarsRequest{} }
func (m *ListCalendarsRequest) String() string { return proto.CompactTextString(m) }
func (*ListCalendarsRequest) ProtoMessage()    {}
func (*ListCalendarsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9d838c4ba0217d, []int{0}
}

func (m *ListCalendarsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCalendarsRequest.Unmarshal(m, b)
}
func (m *ListCalendarsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCalendarsRequest.Marshal(b, m, deterministic)
}
func (m *ListCalendarsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCalendarsRequest.Merge(m, src)
}
func (m *ListCalendarsRequest) XXX_Size() int {
	return xxx_messageInfo_ListCalendarsRequest.Size(m)
}
func (m *ListCalendarsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCalendarsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCalendarsRequest proto.InternalMessageInfo

func (m *ListCalendarsRequest) GetYear() int64 {
	if m != nil {
		return m.Year
	}
	return 0
}

type ListCalendarsResponse struct {
	Year                 int64       `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Calendars            []*Calendar `protobuf:"bytes,2,rep,name=calendars,proto3" json:"calendars,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListCalendarsResponse) Reset()         { *m = ListCalendarsResponse{} }
func (m *ListCalendarsResponse) String() string { return proto.CompactTextString(m) }
func (*ListCalendarsResponse) ProtoMessage()    {}
func (*ListCalendarsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9d838c4ba0217d, []int{1}
}

func (m *ListCalendarsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCalendarsResponse.Unmarshal(m, b)
}
func (m *ListCalendarsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCalendarsResponse.Marshal(b, m, deterministic)
}
func (m *ListCalendarsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCalendarsResponse.Merge(m, src)
}
func (m *ListCalendarsResponse) XXX_Size() int {
	return xxx_messageInfo_ListCalendarsResponse.Size(m)
}
func (m *ListCalendarsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCalendarsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCalendarsResponse proto.InternalMessageInfo

func (m *ListCalendarsResponse) GetYear() int64 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *ListCalendarsResponse) GetCalendars() []*Calendar {
	if m != nil {
		return m.Calendars
	}
	return nil
}

type GetCalendarRequest struct {
	CalendarId           int64    `protobuf:"varint,1,opt,name=calendar_id,json=calendarId,proto3" json:"calendar_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCalendarRequest) Reset()         { *m = GetCalendarRequest{} }
func (m *GetCalendarRequest) String() string { return proto.CompactTextString(m) }
func (*GetCalendarRequest) ProtoMessage()    {}
func (*GetCalendarRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9d838c4ba0217d, []int{2}
}

func (m *GetCalendarRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCalendarRequest.Unmarshal(m, b)
}
func (m *GetCalendarRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCalendarRequest.Marshal(b, m, deterministic)
}
func (m *GetCalendarRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCalendarRequest.Merge(m, src)
}
func (m *GetCalendarRequest) XXX_Size() int {
	return xxx_messageInfo_GetCalendarRequest.Size(m)
}
func (m *GetCalendarRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCalendarRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCalendarRequest proto.InternalMessageInfo

func (m *GetCalendarRequest) GetCalendarId() int64 {
	if m != nil {
		return m.CalendarId
	}
	return 0
}

type GetCalendarResponse struct {
	Calendar             *Calendar `protobuf:"bytes,1,opt,name=calendar,proto3" json:"calendar,omitempty"`
	Entries              []*Entry  `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetCalendarResponse) Reset()         { *m = GetCalendarResponse{} }
func (m *GetCalendarResponse) String() string { return proto.CompactTextString(m) }
func (*GetCalendarResponse) ProtoMessage()    {}
func (*GetCalendarResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9d838c4ba0217d, []int{3}
}

func (m *GetCalendarResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCalendarResponse.Unmarshal(m, b)
}
func (m *GetCalendarResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCalendarResponse.Marshal(b, m, deterministic)
}
func (m *GetCalendarResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCalendarResponse.Merge(m, src)
}
func (m *GetCalendarResponse) XXX_Size() int {
	return xxx_messageInfo_GetCalendarResponse.Size(m)
}
func (m *GetCalendarResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCalendarResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCalendarResponse proto.InternalMessageInfo

func (m *GetCalendarResponse) GetCalendar() *Calendar {
	if m != nil {
		return m.Calendar
	}
	return nil
}

func (m *GetCalendarResponse) GetEntries() []*Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type CreateCalendarRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCalendarRequest) Reset()         { *m = CreateCalendarRequest{} }
func (m *CreateCalendarRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCalendarRequest) ProtoMessage()    {}
func (*CreateCalendarRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9d838c4ba0217d, []int{4}
}

func (m *CreateCalendarRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCalendarRequest.Unmarshal(m, b)
}
func (m *CreateCalendarRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCalendarRequest.Marshal(b, m, deterministic)
}
func (m *CreateCalendarRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCalendarRequest.Merge(m, src)
}
func (m *CreateCalendarRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCalendarRequest.Size(m)
}
func (m *CreateCalendarRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCalendarRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCalendarRequest proto.InternalMessageInfo

func (m *CreateCalendarRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateCalendarRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type UpdateCalendarRequest struct {
	CalendarId           int64    `protobuf:"varint,1,opt,name=calendar_id,json=calendarId,proto3" json:"calendar_id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCalendarRequest) Reset()         { *m = UpdateCalendarRequest{} }
func (m *UpdateCalendarRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCalendarRequest) ProtoMessage()    {}
func (*UpdateCalendarRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9d838c4ba0217d, []int{5}
}

func (m *UpdateCalendarRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCalendarRequest.Unmarshal(m, b)
}
func (m *UpdateCalendarRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCalendarRequest.Marshal(b, m, deterministic)
}
func (m *UpdateCalendarRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCalendarRequest.Merge(m, src)
}
func (m *UpdateCalendarRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCalendarRequest.Size(m)
}
func (m *UpdateCalendarRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCalendarRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCalendarRequest proto.InternalMessageInfo

func (m *UpdateCalendarRequest) GetCalendarId() int64 {
	if m != nil {
		return m.CalendarId
	}
	return 0
}

func (m *UpdateCalendarRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdateCalendarRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type DeleteCalendarRequest struct {
	CalendarId           int64    `protobuf:"varint,1,opt,name=calendar_id,json=calendarId,proto3" json:"calendar_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCalendarRequest) Reset()         { *m = DeleteCalendarRequest{} }
func (m *DeleteCalendarRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCalendarRequest) ProtoMessage()    {}
func (*DeleteCalendarRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9d838c4ba0217d, []int{6}
}

func (m *DeleteCalendarRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCalendarRequest.Unmarshal(m, b)
}
func (m *DeleteCalendarRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCalendarRequest.Marshal(b, m, deterministic)
}
func (m *DeleteCalendarRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCalendarRequest.Merge(m, src)
}
func (m *DeleteCalendarRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCalendarRequest.Size(m)
}
func (m *DeleteCalendarRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCalendarRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCalendarRequest proto.InternalMessageInfo

func (m *DeleteCalendarRequest) GetCalendarId() int64 {
	if m != nil {
		return m.CalendarId
	}
	return 0
}

type CreateEntryRequest struct {
	CalendarId           int64    `protobuf:"varint,1,opt,name=calendar_id,json=calendarId,proto3" json:"calendar_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEntryRequest) Reset()         { *m = CreateEntryRequest{} }
func (m *CreateEntryRequest) String() string { return proto.CompactTextString(m) }
func (*CreateEntryRequest) ProtoMessage()    {}
func (*CreateEntryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9d838c4ba0217d, []int{7}
}

func (m *CreateEntryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEntryRequest.Unmarshal(m, b)
}
func (m *CreateEntryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEntryRequest.Marshal(b, m, deterministic)
}
func (m *CreateEntryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEntryRequest.Merge(m, src)
}
func (m *CreateEntryRequest) XXX_Size() int {
	return xxx_messageInfo_CreateEntryRequest.Size(m)
}
func (m *CreateEntryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEntryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEntryRequest proto.InternalMessageInfo

func (m *CreateEntryRequest) GetCalendarId() int64 {
	if m != nil {
		return m.CalendarId
	}
	return 0
}

type UpdateEntryRequest struct {
	EntryId              int64    `protobuf:"varint,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	Comment              string   `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateEntryRequest) Reset()         { *m = UpdateEntryRequest{} }
func (m *UpdateEntryRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateEntryRequest) ProtoMessage()    {}
func (*UpdateEntryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9d838c4ba0217d, []int{8}
}

func (m *UpdateEntryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateEntryRequest.Unmarshal(m, b)
}
func (m *UpdateEntryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateEntryRequest.Marshal(b, m, deterministic)
}
func (m *UpdateEntryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateEntryRequest.Merge(m, src)
}
func (m *UpdateEntryRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateEntryRequest.Size(m)
}
func (m *UpdateEntryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateEntryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateEntryRequest proto.InternalMessageInfo

func (m *UpdateEntryRequest) GetEntryId() int64 {
	if m != nil {
		return m.EntryId
	}
	return 0
}

func (m *UpdateEntryRequest) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *UpdateEntryRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type DeleteEntryRequest struct {
	EntryId              int64    `protobuf:"varint,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteEntryRequest) Reset()         { *m = DeleteEntryRequest{} }
func (m *DeleteEntryRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteEntryRequest) ProtoMessage()    {}
func (*DeleteEntryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9d838c4ba0217d, []int{9}
}

func (m *DeleteEntryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteEntryRequest.Unmarshal(m, b)
}
func (m *DeleteEntryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteEntryRequest.Marshal(b, m, deterministic)
}
func (m *DeleteEntryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteEntryRequest.Merge(m, src)
}
func (m *DeleteEntryRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteEntryRequest.Size(m)
}
func (m *DeleteEntryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteEntryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteEntryRequest proto.InternalMessageInfo

func (m *DeleteEntryRequest) GetEntryId() int64 {
	if m != nil {
		return m.EntryId
	}
	return 0
}

type SignInRequest struct {
	Jwt                  string   `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInRequest) Reset()         { *m = SignInRequest{} }
func (m *SignInRequest) String() string { return proto.CompactTextString(m) }
func (*SignInRequest) ProtoMessage()    {}
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9d838c4ba0217d, []int{10}
}

func (m *SignInRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInRequest.Unmarshal(m, b)
}
func (m *SignInRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInRequest.Marshal(b, m, deterministic)
}
func (m *SignInRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInRequest.Merge(m, src)
}
func (m *SignInRequest) XXX_Size() int {
	return xxx_messageInfo_SignInRequest.Size(m)
}
func (m *SignInRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignInRequest proto.InternalMessageInfo

func (m *SignInRequest) GetJwt() string {
	if m != nil {
		return m.Jwt
	}
	return ""
}

func init() {
	proto.RegisterType((*ListCalendarsRequest)(nil), "adventar.v1.ListCalendarsRequest")
	proto.RegisterType((*ListCalendarsResponse)(nil), "adventar.v1.ListCalendarsResponse")
	proto.RegisterType((*GetCalendarRequest)(nil), "adventar.v1.GetCalendarRequest")
	proto.RegisterType((*GetCalendarResponse)(nil), "adventar.v1.GetCalendarResponse")
	proto.RegisterType((*CreateCalendarRequest)(nil), "adventar.v1.CreateCalendarRequest")
	proto.RegisterType((*UpdateCalendarRequest)(nil), "adventar.v1.UpdateCalendarRequest")
	proto.RegisterType((*DeleteCalendarRequest)(nil), "adventar.v1.DeleteCalendarRequest")
	proto.RegisterType((*CreateEntryRequest)(nil), "adventar.v1.CreateEntryRequest")
	proto.RegisterType((*UpdateEntryRequest)(nil), "adventar.v1.UpdateEntryRequest")
	proto.RegisterType((*DeleteEntryRequest)(nil), "adventar.v1.DeleteEntryRequest")
	proto.RegisterType((*SignInRequest)(nil), "adventar.v1.SignInRequest")
}

func init() { proto.RegisterFile("adventar/v1/rpc_messages.proto", fileDescriptor_9c9d838c4ba0217d) }

var fileDescriptor_9c9d838c4ba0217d = []byte{
	// 369 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x5f, 0x4b, 0xe3, 0x40,
	0x14, 0xc5, 0x69, 0xb3, 0xbb, 0x6d, 0x6f, 0x58, 0x28, 0xb3, 0x0d, 0x64, 0x15, 0xb4, 0xce, 0x53,
	0x11, 0x49, 0xa9, 0x45, 0xf0, 0xbd, 0x8a, 0x14, 0x04, 0x21, 0xe2, 0x93, 0x0f, 0x35, 0x66, 0x2e,
	0x65, 0x24, 0x9d, 0xc4, 0x99, 0x69, 0x24, 0xdf, 0x5e, 0xf2, 0x67, 0xda, 0xa6, 0x56, 0xad, 0x6f,
	0x37, 0x33, 0xbf, 0x73, 0xcf, 0xb9, 0x77, 0x08, 0x1c, 0x05, 0x2c, 0x45, 0xa1, 0x03, 0x39, 0x4c,
	0x47, 0x43, 0x99, 0x84, 0xb3, 0x05, 0x2a, 0x15, 0xcc, 0x51, 0x79, 0x89, 0x8c, 0x75, 0x4c, 0x6c,
	0x73, 0xef, 0xa5, 0xa3, 0x83, 0xc3, 0x1a, 0x8c, 0x2a, 0x5e, 0xca, 0xd0, 0x90, 0xf4, 0x14, 0x7a,
	0xb7, 0x5c, 0xe9, 0x49, 0x10, 0xa1, 0x60, 0x81, 0x54, 0x3e, 0xbe, 0x2e, 0x51, 0x69, 0x42, 0xe0,
	0x57, 0x86, 0x81, 0x74, 0x1b, 0xfd, 0xc6, 0xc0, 0xf2, 0x8b, 0x9a, 0x3e, 0x81, 0xb3, 0xc5, 0xaa,
	0x24, 0x16, 0x0a, 0x77, 0xc1, 0x64, 0x0c, 0x9d, 0xd0, 0x80, 0x6e, 0xb3, 0x6f, 0x0d, 0xec, 0x73,
	0xc7, 0xdb, 0x88, 0xe5, 0x99, 0x36, 0xfe, 0x9a, 0xa3, 0x17, 0x40, 0x6e, 0x70, 0x65, 0x60, 0xb2,
	0x1c, 0x83, 0x6d, 0x90, 0x19, 0x67, 0x95, 0x0b, 0x98, 0xa3, 0x29, 0xa3, 0x29, 0xfc, 0xab, 0xc9,
	0xaa, 0x58, 0x23, 0x68, 0x1b, 0xa8, 0x10, 0x7d, 0x9a, 0x60, 0x85, 0x91, 0x33, 0x68, 0xa1, 0xd0,
	0x92, 0xa3, 0xc9, 0x4c, 0x6a, 0x8a, 0x6b, 0xa1, 0x65, 0xe6, 0x1b, 0x84, 0xde, 0x81, 0x33, 0x91,
	0x18, 0x68, 0xdc, 0x4e, 0xdc, 0x83, 0xdf, 0x9a, 0xeb, 0x08, 0x0b, 0xdb, 0x8e, 0x5f, 0x7e, 0x90,
	0x3e, 0xd8, 0x0c, 0x55, 0x28, 0x79, 0xa2, 0x79, 0x2c, 0xdc, 0x66, 0x71, 0xb7, 0x79, 0x44, 0x13,
	0x70, 0x1e, 0x12, 0xb6, 0xa3, 0xe1, 0x77, 0x2b, 0x58, 0x3b, 0x36, 0xbf, 0x70, 0xb4, 0x3e, 0x3a,
	0x5e, 0x82, 0x73, 0x85, 0x11, 0xfe, 0xdc, 0x31, 0x7f, 0xab, 0x72, 0xf8, 0x72, 0x29, 0xfb, 0xca,
	0x1e, 0x81, 0x94, 0x23, 0xd6, 0x64, 0xff, 0xa1, 0x9d, 0x2f, 0x35, 0x5b, 0x6b, 0x8a, 0x25, 0x67,
	0x53, 0x46, 0x5c, 0x68, 0x85, 0xf1, 0x62, 0x81, 0x42, 0x57, 0xb3, 0x99, 0x4f, 0xd2, 0x05, 0x6b,
	0x29, 0xa3, 0x6a, 0xaa, 0xbc, 0xa4, 0x43, 0x20, 0xe5, 0x34, 0x7b, 0x36, 0xa7, 0x27, 0xf0, 0xf7,
	0x9e, 0xcf, 0xc5, 0x54, 0x18, 0xb6, 0x0b, 0xd6, 0xcb, 0x9b, 0xae, 0xde, 0x2d, 0x2f, 0x9f, 0xff,
	0x14, 0x3f, 0xca, 0xf8, 0x3d, 0x00, 0x00, 0xff, 0xff, 0x20, 0x63, 0xcb, 0xe4, 0x74, 0x03, 0x00,
	0x00,
}
