service: adventar-image-server

plugins:
 - serverless-apigw-binary

provider:
  name: aws
  stage: prod
  architecture: arm64
  runtime: provided.al2
  region: ap-northeast-1
  deploymentBucket:
    name: adventar
  deploymentPrefix: serverless-deploy
  environment:
    IMAGE_DIGEST_SALT: ${env:IMAGE_DIGEST_SALT}

custom:
  apigwBinary:
    types:
      - '*/*'

package:
  exclude:
    - ./**
  include:
    - ./bootstrap

functions:
  main:
    handler: bootstrap
    events:
      - http:
          method: GET
          path: img/{digest}
