// Code generated by protoc-gen-go. DO NOT EDIT.
// source: adventar/v1/rpc_messages.proto

package adventar_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListCalendarsRequest struct {
	Year                 int64    `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Query                string   `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	PageSize             int32    `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCalendarsRequest) Reset()         { *m = ListCalendarsRequest{} }
func (m *ListCalendarsRequest) String() string { return proto.CompactTextString(m) }
func (*ListCalendarsRequest) ProtoMessage()    {}
func (*ListCalendarsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9d838c4ba0217d, []int{0}
}

func (m *ListCalendarsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCalendarsRequest.Unmarshal(m, b)
}
func (m *ListCalendarsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCalendarsRequest.Marshal(b, m, deterministic)
}
func (m *ListCalendarsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCalendarsRequest.Merge(m, src)
}
func (m *ListCalendarsRequest) XXX_Size() int {
	return xxx_messageInfo_ListCalendarsRequest.Size(m)
}
func (m *ListCalendarsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCalendarsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCalendarsRequest proto.InternalMessageInfo

func (m *ListCalendarsRequest) GetYear() int64 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *ListCalendarsRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ListCalendarsRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *ListCalendarsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type ListCalendarsResponse struct {
	Calendars            []*Calendar `protobuf:"bytes,1,rep,name=calendars,proto3" json:"calendars,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListCalendarsResponse) Reset()         { *m = ListCalendarsResponse{} }
func (m *ListCalendarsResponse) String() string { return proto.CompactTextString(m) }
func (*ListCalendarsResponse) ProtoMessage()    {}
func (*ListCalendarsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9d838c4ba0217d, []int{1}
}

func (m *ListCalendarsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCalendarsResponse.Unmarshal(m, b)
}
func (m *ListCalendarsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCalendarsResponse.Marshal(b, m, deterministic)
}
func (m *ListCalendarsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCalendarsResponse.Merge(m, src)
}
func (m *ListCalendarsResponse) XXX_Size() int {
	return xxx_messageInfo_ListCalendarsResponse.Size(m)
}
func (m *ListCalendarsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCalendarsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCalendarsResponse proto.InternalMessageInfo

func (m *ListCalendarsResponse) GetCalendars() []*Calendar {
	if m != nil {
		return m.Calendars
	}
	return nil
}

type GetCalendarRequest struct {
	CalendarId           int64    `protobuf:"varint,1,opt,name=calendar_id,json=calendarId,proto3" json:"calendar_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCalendarRequest) Reset()         { *m = GetCalendarRequest{} }
func (m *GetCalendarRequest) String() string { return proto.CompactTextString(m) }
func (*GetCalendarRequest) ProtoMessage()    {}
func (*GetCalendarRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9d838c4ba0217d, []int{2}
}

func (m *GetCalendarRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCalendarRequest.Unmarshal(m, b)
}
func (m *GetCalendarRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCalendarRequest.Marshal(b, m, deterministic)
}
func (m *GetCalendarRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCalendarRequest.Merge(m, src)
}
func (m *GetCalendarRequest) XXX_Size() int {
	return xxx_messageInfo_GetCalendarRequest.Size(m)
}
func (m *GetCalendarRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCalendarRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCalendarRequest proto.InternalMessageInfo

func (m *GetCalendarRequest) GetCalendarId() int64 {
	if m != nil {
		return m.CalendarId
	}
	return 0
}

type GetCalendarResponse struct {
	Calendar             *Calendar `protobuf:"bytes,1,opt,name=calendar,proto3" json:"calendar,omitempty"`
	Entries              []*Entry  `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetCalendarResponse) Reset()         { *m = GetCalendarResponse{} }
func (m *GetCalendarResponse) String() string { return proto.CompactTextString(m) }
func (*GetCalendarResponse) ProtoMessage()    {}
func (*GetCalendarResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9d838c4ba0217d, []int{3}
}

func (m *GetCalendarResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCalendarResponse.Unmarshal(m, b)
}
func (m *GetCalendarResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCalendarResponse.Marshal(b, m, deterministic)
}
func (m *GetCalendarResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCalendarResponse.Merge(m, src)
}
func (m *GetCalendarResponse) XXX_Size() int {
	return xxx_messageInfo_GetCalendarResponse.Size(m)
}
func (m *GetCalendarResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCalendarResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCalendarResponse proto.InternalMessageInfo

func (m *GetCalendarResponse) GetCalendar() *Calendar {
	if m != nil {
		return m.Calendar
	}
	return nil
}

func (m *GetCalendarResponse) GetEntries() []*Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type CreateCalendarRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCalendarRequest) Reset()         { *m = CreateCalendarRequest{} }
func (m *CreateCalendarRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCalendarRequest) ProtoMessage()    {}
func (*CreateCalendarRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9d838c4ba0217d, []int{4}
}

func (m *CreateCalendarRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCalendarRequest.Unmarshal(m, b)
}
func (m *CreateCalendarRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCalendarRequest.Marshal(b, m, deterministic)
}
func (m *CreateCalendarRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCalendarRequest.Merge(m, src)
}
func (m *CreateCalendarRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCalendarRequest.Size(m)
}
func (m *CreateCalendarRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCalendarRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCalendarRequest proto.InternalMessageInfo

func (m *CreateCalendarRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateCalendarRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type UpdateCalendarRequest struct {
	CalendarId           int64    `protobuf:"varint,1,opt,name=calendar_id,json=calendarId,proto3" json:"calendar_id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCalendarRequest) Reset()         { *m = UpdateCalendarRequest{} }
func (m *UpdateCalendarRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCalendarRequest) ProtoMessage()    {}
func (*UpdateCalendarRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9d838c4ba0217d, []int{5}
}

func (m *UpdateCalendarRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCalendarRequest.Unmarshal(m, b)
}
func (m *UpdateCalendarRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCalendarRequest.Marshal(b, m, deterministic)
}
func (m *UpdateCalendarRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCalendarRequest.Merge(m, src)
}
func (m *UpdateCalendarRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCalendarRequest.Size(m)
}
func (m *UpdateCalendarRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCalendarRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCalendarRequest proto.InternalMessageInfo

func (m *UpdateCalendarRequest) GetCalendarId() int64 {
	if m != nil {
		return m.CalendarId
	}
	return 0
}

func (m *UpdateCalendarRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdateCalendarRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type DeleteCalendarRequest struct {
	CalendarId           int64    `protobuf:"varint,1,opt,name=calendar_id,json=calendarId,proto3" json:"calendar_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCalendarRequest) Reset()         { *m = DeleteCalendarRequest{} }
func (m *DeleteCalendarRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCalendarRequest) ProtoMessage()    {}
func (*DeleteCalendarRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9d838c4ba0217d, []int{6}
}

func (m *DeleteCalendarRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCalendarRequest.Unmarshal(m, b)
}
func (m *DeleteCalendarRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCalendarRequest.Marshal(b, m, deterministic)
}
func (m *DeleteCalendarRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCalendarRequest.Merge(m, src)
}
func (m *DeleteCalendarRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCalendarRequest.Size(m)
}
func (m *DeleteCalendarRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCalendarRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCalendarRequest proto.InternalMessageInfo

func (m *DeleteCalendarRequest) GetCalendarId() int64 {
	if m != nil {
		return m.CalendarId
	}
	return 0
}

type ListCalendarStatsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCalendarStatsRequest) Reset()         { *m = ListCalendarStatsRequest{} }
func (m *ListCalendarStatsRequest) String() string { return proto.CompactTextString(m) }
func (*ListCalendarStatsRequest) ProtoMessage()    {}
func (*ListCalendarStatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9d838c4ba0217d, []int{7}
}

func (m *ListCalendarStatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCalendarStatsRequest.Unmarshal(m, b)
}
func (m *ListCalendarStatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCalendarStatsRequest.Marshal(b, m, deterministic)
}
func (m *ListCalendarStatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCalendarStatsRequest.Merge(m, src)
}
func (m *ListCalendarStatsRequest) XXX_Size() int {
	return xxx_messageInfo_ListCalendarStatsRequest.Size(m)
}
func (m *ListCalendarStatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCalendarStatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCalendarStatsRequest proto.InternalMessageInfo

type ListCalendarStatsResponse struct {
	CalendarStats        []*CalendarStat `protobuf:"bytes,1,rep,name=calendar_stats,json=calendarStats,proto3" json:"calendar_stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListCalendarStatsResponse) Reset()         { *m = ListCalendarStatsResponse{} }
func (m *ListCalendarStatsResponse) String() string { return proto.CompactTextString(m) }
func (*ListCalendarStatsResponse) ProtoMessage()    {}
func (*ListCalendarStatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9d838c4ba0217d, []int{8}
}

func (m *ListCalendarStatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCalendarStatsResponse.Unmarshal(m, b)
}
func (m *ListCalendarStatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCalendarStatsResponse.Marshal(b, m, deterministic)
}
func (m *ListCalendarStatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCalendarStatsResponse.Merge(m, src)
}
func (m *ListCalendarStatsResponse) XXX_Size() int {
	return xxx_messageInfo_ListCalendarStatsResponse.Size(m)
}
func (m *ListCalendarStatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCalendarStatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCalendarStatsResponse proto.InternalMessageInfo

func (m *ListCalendarStatsResponse) GetCalendarStats() []*CalendarStat {
	if m != nil {
		return m.CalendarStats
	}
	return nil
}

type ListEntriesRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Year                 int32    `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListEntriesRequest) Reset()         { *m = ListEntriesRequest{} }
func (m *ListEntriesRequest) String() string { return proto.CompactTextString(m) }
func (*ListEntriesRequest) ProtoMessage()    {}
func (*ListEntriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9d838c4ba0217d, []int{9}
}

func (m *ListEntriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEntriesRequest.Unmarshal(m, b)
}
func (m *ListEntriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEntriesRequest.Marshal(b, m, deterministic)
}
func (m *ListEntriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEntriesRequest.Merge(m, src)
}
func (m *ListEntriesRequest) XXX_Size() int {
	return xxx_messageInfo_ListEntriesRequest.Size(m)
}
func (m *ListEntriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEntriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListEntriesRequest proto.InternalMessageInfo

func (m *ListEntriesRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ListEntriesRequest) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

type ListEntriesResponse struct {
	Entries              []*Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListEntriesResponse) Reset()         { *m = ListEntriesResponse{} }
func (m *ListEntriesResponse) String() string { return proto.CompactTextString(m) }
func (*ListEntriesResponse) ProtoMessage()    {}
func (*ListEntriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9d838c4ba0217d, []int{10}
}

func (m *ListEntriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEntriesResponse.Unmarshal(m, b)
}
func (m *ListEntriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEntriesResponse.Marshal(b, m, deterministic)
}
func (m *ListEntriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEntriesResponse.Merge(m, src)
}
func (m *ListEntriesResponse) XXX_Size() int {
	return xxx_messageInfo_ListEntriesResponse.Size(m)
}
func (m *ListEntriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEntriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListEntriesResponse proto.InternalMessageInfo

func (m *ListEntriesResponse) GetEntries() []*Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type CreateEntryRequest struct {
	CalendarId           int64    `protobuf:"varint,1,opt,name=calendar_id,json=calendarId,proto3" json:"calendar_id,omitempty"`
	Day                  int32    `protobuf:"varint,2,opt,name=day,proto3" json:"day,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEntryRequest) Reset()         { *m = CreateEntryRequest{} }
func (m *CreateEntryRequest) String() string { return proto.CompactTextString(m) }
func (*CreateEntryRequest) ProtoMessage()    {}
func (*CreateEntryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9d838c4ba0217d, []int{11}
}

func (m *CreateEntryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEntryRequest.Unmarshal(m, b)
}
func (m *CreateEntryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEntryRequest.Marshal(b, m, deterministic)
}
func (m *CreateEntryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEntryRequest.Merge(m, src)
}
func (m *CreateEntryRequest) XXX_Size() int {
	return xxx_messageInfo_CreateEntryRequest.Size(m)
}
func (m *CreateEntryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEntryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEntryRequest proto.InternalMessageInfo

func (m *CreateEntryRequest) GetCalendarId() int64 {
	if m != nil {
		return m.CalendarId
	}
	return 0
}

func (m *CreateEntryRequest) GetDay() int32 {
	if m != nil {
		return m.Day
	}
	return 0
}

type UpdateEntryRequest struct {
	EntryId              int64    `protobuf:"varint,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	Comment              string   `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateEntryRequest) Reset()         { *m = UpdateEntryRequest{} }
func (m *UpdateEntryRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateEntryRequest) ProtoMessage()    {}
func (*UpdateEntryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9d838c4ba0217d, []int{12}
}

func (m *UpdateEntryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateEntryRequest.Unmarshal(m, b)
}
func (m *UpdateEntryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateEntryRequest.Marshal(b, m, deterministic)
}
func (m *UpdateEntryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateEntryRequest.Merge(m, src)
}
func (m *UpdateEntryRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateEntryRequest.Size(m)
}
func (m *UpdateEntryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateEntryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateEntryRequest proto.InternalMessageInfo

func (m *UpdateEntryRequest) GetEntryId() int64 {
	if m != nil {
		return m.EntryId
	}
	return 0
}

func (m *UpdateEntryRequest) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *UpdateEntryRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type DeleteEntryRequest struct {
	EntryId              int64    `protobuf:"varint,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteEntryRequest) Reset()         { *m = DeleteEntryRequest{} }
func (m *DeleteEntryRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteEntryRequest) ProtoMessage()    {}
func (*DeleteEntryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9d838c4ba0217d, []int{13}
}

func (m *DeleteEntryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteEntryRequest.Unmarshal(m, b)
}
func (m *DeleteEntryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteEntryRequest.Marshal(b, m, deterministic)
}
func (m *DeleteEntryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteEntryRequest.Merge(m, src)
}
func (m *DeleteEntryRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteEntryRequest.Size(m)
}
func (m *DeleteEntryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteEntryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteEntryRequest proto.InternalMessageInfo

func (m *DeleteEntryRequest) GetEntryId() int64 {
	if m != nil {
		return m.EntryId
	}
	return 0
}

type SignInRequest struct {
	Jwt                  string   `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	IconUrl              string   `protobuf:"bytes,2,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInRequest) Reset()         { *m = SignInRequest{} }
func (m *SignInRequest) String() string { return proto.CompactTextString(m) }
func (*SignInRequest) ProtoMessage()    {}
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9d838c4ba0217d, []int{14}
}

func (m *SignInRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInRequest.Unmarshal(m, b)
}
func (m *SignInRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInRequest.Marshal(b, m, deterministic)
}
func (m *SignInRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInRequest.Merge(m, src)
}
func (m *SignInRequest) XXX_Size() int {
	return xxx_messageInfo_SignInRequest.Size(m)
}
func (m *SignInRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignInRequest proto.InternalMessageInfo

func (m *SignInRequest) GetJwt() string {
	if m != nil {
		return m.Jwt
	}
	return ""
}

func (m *SignInRequest) GetIconUrl() string {
	if m != nil {
		return m.IconUrl
	}
	return ""
}

type GetUserRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9d838c4ba0217d, []int{15}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type UpdateUserRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9d838c4ba0217d, []int{16}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HealthCheckRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheckRequest) Reset()         { *m = HealthCheckRequest{} }
func (m *HealthCheckRequest) String() string { return proto.CompactTextString(m) }
func (*HealthCheckRequest) ProtoMessage()    {}
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9d838c4ba0217d, []int{17}
}

func (m *HealthCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckRequest.Unmarshal(m, b)
}
func (m *HealthCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckRequest.Marshal(b, m, deterministic)
}
func (m *HealthCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckRequest.Merge(m, src)
}
func (m *HealthCheckRequest) XXX_Size() int {
	return xxx_messageInfo_HealthCheckRequest.Size(m)
}
func (m *HealthCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckRequest proto.InternalMessageInfo

type HealthCheckResponse struct {
	State                string   `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheckResponse) Reset()         { *m = HealthCheckResponse{} }
func (m *HealthCheckResponse) String() string { return proto.CompactTextString(m) }
func (*HealthCheckResponse) ProtoMessage()    {}
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c9d838c4ba0217d, []int{18}
}

func (m *HealthCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckResponse.Unmarshal(m, b)
}
func (m *HealthCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckResponse.Marshal(b, m, deterministic)
}
func (m *HealthCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckResponse.Merge(m, src)
}
func (m *HealthCheckResponse) XXX_Size() int {
	return xxx_messageInfo_HealthCheckResponse.Size(m)
}
func (m *HealthCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckResponse proto.InternalMessageInfo

func (m *HealthCheckResponse) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func init() {
	proto.RegisterType((*ListCalendarsRequest)(nil), "adventar.v1.ListCalendarsRequest")
	proto.RegisterType((*ListCalendarsResponse)(nil), "adventar.v1.ListCalendarsResponse")
	proto.RegisterType((*GetCalendarRequest)(nil), "adventar.v1.GetCalendarRequest")
	proto.RegisterType((*GetCalendarResponse)(nil), "adventar.v1.GetCalendarResponse")
	proto.RegisterType((*CreateCalendarRequest)(nil), "adventar.v1.CreateCalendarRequest")
	proto.RegisterType((*UpdateCalendarRequest)(nil), "adventar.v1.UpdateCalendarRequest")
	proto.RegisterType((*DeleteCalendarRequest)(nil), "adventar.v1.DeleteCalendarRequest")
	proto.RegisterType((*ListCalendarStatsRequest)(nil), "adventar.v1.ListCalendarStatsRequest")
	proto.RegisterType((*ListCalendarStatsResponse)(nil), "adventar.v1.ListCalendarStatsResponse")
	proto.RegisterType((*ListEntriesRequest)(nil), "adventar.v1.ListEntriesRequest")
	proto.RegisterType((*ListEntriesResponse)(nil), "adventar.v1.ListEntriesResponse")
	proto.RegisterType((*CreateEntryRequest)(nil), "adventar.v1.CreateEntryRequest")
	proto.RegisterType((*UpdateEntryRequest)(nil), "adventar.v1.UpdateEntryRequest")
	proto.RegisterType((*DeleteEntryRequest)(nil), "adventar.v1.DeleteEntryRequest")
	proto.RegisterType((*SignInRequest)(nil), "adventar.v1.SignInRequest")
	proto.RegisterType((*GetUserRequest)(nil), "adventar.v1.GetUserRequest")
	proto.RegisterType((*UpdateUserRequest)(nil), "adventar.v1.UpdateUserRequest")
	proto.RegisterType((*HealthCheckRequest)(nil), "adventar.v1.HealthCheckRequest")
	proto.RegisterType((*HealthCheckResponse)(nil), "adventar.v1.HealthCheckResponse")
}

func init() { proto.RegisterFile("adventar/v1/rpc_messages.proto", fileDescriptor_9c9d838c4ba0217d) }

var fileDescriptor_9c9d838c4ba0217d = []byte{
	// 571 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x51, 0x8f, 0xd2, 0x40,
	0x10, 0x4e, 0x29, 0x1c, 0x30, 0xe4, 0x2e, 0xe7, 0x02, 0xb1, 0xdc, 0x25, 0x4a, 0xf6, 0x45, 0x8c,
	0x06, 0x82, 0x17, 0x13, 0x1f, 0x7c, 0xd0, 0xe0, 0x05, 0x49, 0x2e, 0x31, 0x29, 0xe1, 0xc9, 0x18,
	0xb2, 0xb6, 0x13, 0xae, 0x5a, 0xda, 0xde, 0xee, 0x82, 0xe9, 0xfd, 0x7a, 0xb3, 0xdb, 0x2e, 0xb4,
	0x27, 0xca, 0xf9, 0x36, 0x33, 0x3b, 0xf3, 0x7d, 0xdf, 0xf6, 0x9b, 0x2d, 0x3c, 0x63, 0xfe, 0x16,
	0x23, 0xc9, 0xf8, 0x68, 0x3b, 0x1e, 0xf1, 0xc4, 0x5b, 0xae, 0x51, 0x08, 0xb6, 0x42, 0x31, 0x4c,
	0x78, 0x2c, 0x63, 0xd2, 0x32, 0xe7, 0xc3, 0xed, 0xf8, 0xe2, 0xb2, 0xd4, 0x8c, 0x22, 0xde, 0x70,
	0xcf, 0x74, 0xd2, 0x2d, 0x74, 0x6e, 0x02, 0x21, 0x27, 0x2c, 0xc4, 0xc8, 0x67, 0x5c, 0xb8, 0x78,
	0xb7, 0x41, 0x21, 0x09, 0x81, 0x6a, 0x8a, 0x8c, 0x3b, 0x56, 0xdf, 0x1a, 0xd8, 0xae, 0x8e, 0xc9,
	0x53, 0xa8, 0x6f, 0x04, 0xf2, 0x65, 0xe0, 0x3b, 0x15, 0x5d, 0x3e, 0x51, 0xe9, 0xcc, 0x27, 0x1d,
	0xa8, 0xdd, 0x6d, 0x90, 0xa7, 0x8e, 0xdd, 0xb7, 0x06, 0x4d, 0x37, 0x4b, 0xc8, 0x25, 0x34, 0x13,
	0xb6, 0xc2, 0xa5, 0x08, 0xee, 0xd1, 0xa9, 0xf6, 0xad, 0x41, 0xcd, 0x6d, 0xa8, 0xc2, 0x3c, 0xb8,
	0x47, 0x7a, 0x03, 0xdd, 0x07, 0xbc, 0x22, 0x89, 0x23, 0x81, 0xe4, 0x0a, 0x9a, 0x9e, 0x29, 0x3a,
	0x56, 0xdf, 0x1e, 0xb4, 0xde, 0x74, 0x87, 0x85, 0xeb, 0x0c, 0xcd, 0x88, 0xbb, 0xef, 0xa3, 0x6f,
	0x81, 0x4c, 0x71, 0x07, 0x66, 0xee, 0xf0, 0x1c, 0x5a, 0xa6, 0x45, 0x69, 0xce, 0xae, 0x02, 0xa6,
	0x34, 0xf3, 0xe9, 0x16, 0xda, 0xa5, 0xb1, 0x5c, 0xc2, 0x18, 0x1a, 0xa6, 0x49, 0x0f, 0xfd, 0x55,
	0xc1, 0xae, 0x8d, 0xbc, 0x86, 0x3a, 0x46, 0x92, 0x07, 0x28, 0x9c, 0x8a, 0xd6, 0x4c, 0x4a, 0x13,
	0xd7, 0x91, 0xe4, 0xa9, 0x6b, 0x5a, 0xe8, 0x17, 0xe8, 0x4e, 0x38, 0x32, 0x89, 0x0f, 0x15, 0x77,
	0xa0, 0x26, 0x03, 0x19, 0xa2, 0xa6, 0x6d, 0xba, 0x59, 0x42, 0xfa, 0xd0, 0xf2, 0x51, 0x78, 0x3c,
	0x48, 0x64, 0x10, 0x47, 0xfa, 0xdb, 0x37, 0xdd, 0x62, 0x89, 0x26, 0xd0, 0x5d, 0x24, 0xfe, 0x01,
	0xc0, 0x63, 0x9f, 0x60, 0xcf, 0x58, 0xf9, 0x07, 0xa3, 0xfd, 0x27, 0xe3, 0x3b, 0xe8, 0x7e, 0xc2,
	0x10, 0xff, 0x9f, 0x91, 0x5e, 0x80, 0x53, 0x74, 0x7e, 0x2e, 0x99, 0x34, 0x5b, 0x47, 0xbf, 0x41,
	0xef, 0xc0, 0x59, 0x6e, 0xcb, 0x07, 0x38, 0xdb, 0x21, 0x0b, 0x75, 0x92, 0xaf, 0x47, 0xef, 0xa0,
	0x39, 0x6a, 0xd6, 0x3d, 0xf5, 0x8a, 0x48, 0xf4, 0x23, 0x10, 0x05, 0x7f, 0x9d, 0xd9, 0x60, 0x14,
	0x17, 0xd6, 0xda, 0x2a, 0xad, 0xb5, 0x79, 0x03, 0x15, 0xbd, 0xbb, 0x3a, 0xa6, 0x13, 0x68, 0x97,
	0x20, 0x72, 0x6d, 0x05, 0xff, 0xad, 0xe3, 0xfe, 0x4f, 0x81, 0x64, 0xfe, 0x67, 0xf5, 0xc7, 0x7a,
	0x75, 0x0e, 0xb6, 0xcf, 0xd2, 0x5c, 0x8e, 0x0a, 0xe9, 0x57, 0x20, 0x99, 0xef, 0x25, 0xa0, 0x1e,
	0x34, 0x14, 0x53, 0xba, 0x47, 0xd1, 0xcc, 0xe9, 0xcc, 0x27, 0x0e, 0xd4, 0xbd, 0x78, 0xbd, 0xc6,
	0x48, 0xe6, 0x86, 0x9b, 0x54, 0x81, 0x6f, 0x78, 0x98, 0x5b, 0xad, 0x42, 0x3a, 0x02, 0x92, 0x59,
	0xfc, 0x48, 0x70, 0xfa, 0x1e, 0x4e, 0xe7, 0xc1, 0x2a, 0x9a, 0x45, 0xa6, 0xf7, 0x1c, 0xec, 0x1f,
	0xbf, 0x64, 0xbe, 0xcc, 0x2a, 0x54, 0xd3, 0x81, 0x17, 0x47, 0x4b, 0x45, 0x95, 0x0b, 0x50, 0xf9,
	0x82, 0x87, 0xf4, 0x25, 0x9c, 0x4d, 0x51, 0x2e, 0x04, 0xf2, 0x63, 0xc6, 0xd0, 0x17, 0xf0, 0x24,
	0xbb, 0x76, 0xb1, 0x9b, 0x40, 0x35, 0x62, 0x6b, 0xf3, 0x74, 0x74, 0x4c, 0x3b, 0x40, 0x3e, 0x23,
	0x0b, 0xe5, 0xed, 0xe4, 0x16, 0xbd, 0x9f, 0x66, 0xcb, 0x5e, 0x41, 0xbb, 0x54, 0xcd, 0x3d, 0xec,
	0x40, 0x4d, 0xad, 0xd5, 0xee, 0xf1, 0xe9, 0xe4, 0xfb, 0x89, 0xfe, 0x4f, 0x5e, 0xfd, 0x0e, 0x00,
	0x00, 0xff, 0xff, 0x92, 0xf2, 0xac, 0xeb, 0x73, 0x05, 0x00, 0x00,
}
